/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedTutupKasIndexRouteImport } from './routes/_authenticated/tutup-kas/index'
import { Route as AuthenticatedSupplierIndexRouteImport } from './routes/_authenticated/supplier/index'
import { Route as AuthenticatedStokIndexRouteImport } from './routes/_authenticated/stok/index'
import { Route as AuthenticatedSimpanPinjamIndexRouteImport } from './routes/_authenticated/simpan-pinjam/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedRapatIndexRouteImport } from './routes/_authenticated/rapat/index'
import { Route as AuthenticatedPosIndexRouteImport } from './routes/_authenticated/pos/index'
import { Route as AuthenticatedPenukaranPoinIndexRouteImport } from './routes/_authenticated/penukaran-poin/index'
import { Route as AuthenticatedPengumumanIndexRouteImport } from './routes/_authenticated/pengumuman/index'
import { Route as AuthenticatedPengawasanIndexRouteImport } from './routes/_authenticated/pengawasan/index'
import { Route as AuthenticatedLedgerIndexRouteImport } from './routes/_authenticated/ledger/index'
import { Route as AuthenticatedLaporanIndexRouteImport } from './routes/_authenticated/laporan/index'
import { Route as AuthenticatedKontrakIndexRouteImport } from './routes/_authenticated/kontrak/index'
import { Route as AuthenticatedKonfigurasiShuIndexRouteImport } from './routes/_authenticated/konfigurasi-shu/index'
import { Route as AuthenticatedKasMasukIndexRouteImport } from './routes/_authenticated/kas-masuk/index'
import { Route as AuthenticatedKasKeluarIndexRouteImport } from './routes/_authenticated/kas-keluar/index'
import { Route as AuthenticatedDokumenIndexRouteImport } from './routes/_authenticated/dokumen/index'
import { Route as AuthenticatedAuditIndexRouteImport } from './routes/_authenticated/audit/index'
import { Route as AuthenticatedApprovalIndexRouteImport } from './routes/_authenticated/approval/index'
import { Route as AuthenticatedAnggotaIndexRouteImport } from './routes/_authenticated/anggota/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedAdminProfilIndexRouteImport } from './routes/_authenticated/admin/profil/index'
import { Route as AuthenticatedAdminKoppoinIndexRouteImport } from './routes/_authenticated/admin/koppoin/index'
import { Route as AuthenticatedAdminKeuanganIndexRouteImport } from './routes/_authenticated/admin/keuangan/index'
import { Route as AuthenticatedAdminAkunIndexRouteImport } from './routes/_authenticated/admin/akun/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTutupKasIndexRoute =
  AuthenticatedTutupKasIndexRouteImport.update({
    id: '/tutup-kas/',
    path: '/tutup-kas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierIndexRoute =
  AuthenticatedSupplierIndexRouteImport.update({
    id: '/supplier/',
    path: '/supplier/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStokIndexRoute = AuthenticatedStokIndexRouteImport.update({
  id: '/stok/',
  path: '/stok/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSimpanPinjamIndexRoute =
  AuthenticatedSimpanPinjamIndexRouteImport.update({
    id: '/simpan-pinjam/',
    path: '/simpan-pinjam/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedRapatIndexRoute = AuthenticatedRapatIndexRouteImport.update({
  id: '/rapat/',
  path: '/rapat/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPosIndexRoute = AuthenticatedPosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPenukaranPoinIndexRoute =
  AuthenticatedPenukaranPoinIndexRouteImport.update({
    id: '/penukaran-poin/',
    path: '/penukaran-poin/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPengumumanIndexRoute =
  AuthenticatedPengumumanIndexRouteImport.update({
    id: '/pengumuman/',
    path: '/pengumuman/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPengawasanIndexRoute =
  AuthenticatedPengawasanIndexRouteImport.update({
    id: '/pengawasan/',
    path: '/pengawasan/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLedgerIndexRoute =
  AuthenticatedLedgerIndexRouteImport.update({
    id: '/ledger/',
    path: '/ledger/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLaporanIndexRoute =
  AuthenticatedLaporanIndexRouteImport.update({
    id: '/laporan/',
    path: '/laporan/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKontrakIndexRoute =
  AuthenticatedKontrakIndexRouteImport.update({
    id: '/kontrak/',
    path: '/kontrak/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKonfigurasiShuIndexRoute =
  AuthenticatedKonfigurasiShuIndexRouteImport.update({
    id: '/konfigurasi-shu/',
    path: '/konfigurasi-shu/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKasMasukIndexRoute =
  AuthenticatedKasMasukIndexRouteImport.update({
    id: '/kas-masuk/',
    path: '/kas-masuk/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKasKeluarIndexRoute =
  AuthenticatedKasKeluarIndexRouteImport.update({
    id: '/kas-keluar/',
    path: '/kas-keluar/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDokumenIndexRoute =
  AuthenticatedDokumenIndexRouteImport.update({
    id: '/dokumen/',
    path: '/dokumen/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditIndexRoute = AuthenticatedAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalIndexRoute =
  AuthenticatedApprovalIndexRouteImport.update({
    id: '/approval/',
    path: '/approval/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnggotaIndexRoute =
  AuthenticatedAnggotaIndexRouteImport.update({
    id: '/anggota/',
    path: '/anggota/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProfilIndexRoute =
  AuthenticatedAdminProfilIndexRouteImport.update({
    id: '/admin/profil/',
    path: '/admin/profil/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminKoppoinIndexRoute =
  AuthenticatedAdminKoppoinIndexRouteImport.update({
    id: '/admin/koppoin/',
    path: '/admin/koppoin/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminKeuanganIndexRoute =
  AuthenticatedAdminKeuanganIndexRouteImport.update({
    id: '/admin/keuangan/',
    path: '/admin/keuangan/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAkunIndexRoute =
  AuthenticatedAdminAkunIndexRouteImport.update({
    id: '/admin/akun/',
    path: '/admin/akun/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/anggota/': typeof AuthenticatedAnggotaIndexRoute
  '/approval/': typeof AuthenticatedApprovalIndexRoute
  '/audit/': typeof AuthenticatedAuditIndexRoute
  '/dokumen/': typeof AuthenticatedDokumenIndexRoute
  '/kas-keluar/': typeof AuthenticatedKasKeluarIndexRoute
  '/kas-masuk/': typeof AuthenticatedKasMasukIndexRoute
  '/konfigurasi-shu/': typeof AuthenticatedKonfigurasiShuIndexRoute
  '/kontrak/': typeof AuthenticatedKontrakIndexRoute
  '/laporan/': typeof AuthenticatedLaporanIndexRoute
  '/ledger/': typeof AuthenticatedLedgerIndexRoute
  '/pengawasan/': typeof AuthenticatedPengawasanIndexRoute
  '/pengumuman/': typeof AuthenticatedPengumumanIndexRoute
  '/penukaran-poin/': typeof AuthenticatedPenukaranPoinIndexRoute
  '/pos/': typeof AuthenticatedPosIndexRoute
  '/rapat/': typeof AuthenticatedRapatIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/simpan-pinjam/': typeof AuthenticatedSimpanPinjamIndexRoute
  '/stok/': typeof AuthenticatedStokIndexRoute
  '/supplier/': typeof AuthenticatedSupplierIndexRoute
  '/tutup-kas/': typeof AuthenticatedTutupKasIndexRoute
  '/admin/akun/': typeof AuthenticatedAdminAkunIndexRoute
  '/admin/keuangan/': typeof AuthenticatedAdminKeuanganIndexRoute
  '/admin/koppoin/': typeof AuthenticatedAdminKoppoinIndexRoute
  '/admin/profil/': typeof AuthenticatedAdminProfilIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/anggota': typeof AuthenticatedAnggotaIndexRoute
  '/approval': typeof AuthenticatedApprovalIndexRoute
  '/audit': typeof AuthenticatedAuditIndexRoute
  '/dokumen': typeof AuthenticatedDokumenIndexRoute
  '/kas-keluar': typeof AuthenticatedKasKeluarIndexRoute
  '/kas-masuk': typeof AuthenticatedKasMasukIndexRoute
  '/konfigurasi-shu': typeof AuthenticatedKonfigurasiShuIndexRoute
  '/kontrak': typeof AuthenticatedKontrakIndexRoute
  '/laporan': typeof AuthenticatedLaporanIndexRoute
  '/ledger': typeof AuthenticatedLedgerIndexRoute
  '/pengawasan': typeof AuthenticatedPengawasanIndexRoute
  '/pengumuman': typeof AuthenticatedPengumumanIndexRoute
  '/penukaran-poin': typeof AuthenticatedPenukaranPoinIndexRoute
  '/pos': typeof AuthenticatedPosIndexRoute
  '/rapat': typeof AuthenticatedRapatIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/simpan-pinjam': typeof AuthenticatedSimpanPinjamIndexRoute
  '/stok': typeof AuthenticatedStokIndexRoute
  '/supplier': typeof AuthenticatedSupplierIndexRoute
  '/tutup-kas': typeof AuthenticatedTutupKasIndexRoute
  '/admin/akun': typeof AuthenticatedAdminAkunIndexRoute
  '/admin/keuangan': typeof AuthenticatedAdminKeuanganIndexRoute
  '/admin/koppoin': typeof AuthenticatedAdminKoppoinIndexRoute
  '/admin/profil': typeof AuthenticatedAdminProfilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/anggota/': typeof AuthenticatedAnggotaIndexRoute
  '/_authenticated/approval/': typeof AuthenticatedApprovalIndexRoute
  '/_authenticated/audit/': typeof AuthenticatedAuditIndexRoute
  '/_authenticated/dokumen/': typeof AuthenticatedDokumenIndexRoute
  '/_authenticated/kas-keluar/': typeof AuthenticatedKasKeluarIndexRoute
  '/_authenticated/kas-masuk/': typeof AuthenticatedKasMasukIndexRoute
  '/_authenticated/konfigurasi-shu/': typeof AuthenticatedKonfigurasiShuIndexRoute
  '/_authenticated/kontrak/': typeof AuthenticatedKontrakIndexRoute
  '/_authenticated/laporan/': typeof AuthenticatedLaporanIndexRoute
  '/_authenticated/ledger/': typeof AuthenticatedLedgerIndexRoute
  '/_authenticated/pengawasan/': typeof AuthenticatedPengawasanIndexRoute
  '/_authenticated/pengumuman/': typeof AuthenticatedPengumumanIndexRoute
  '/_authenticated/penukaran-poin/': typeof AuthenticatedPenukaranPoinIndexRoute
  '/_authenticated/pos/': typeof AuthenticatedPosIndexRoute
  '/_authenticated/rapat/': typeof AuthenticatedRapatIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/simpan-pinjam/': typeof AuthenticatedSimpanPinjamIndexRoute
  '/_authenticated/stok/': typeof AuthenticatedStokIndexRoute
  '/_authenticated/supplier/': typeof AuthenticatedSupplierIndexRoute
  '/_authenticated/tutup-kas/': typeof AuthenticatedTutupKasIndexRoute
  '/_authenticated/admin/akun/': typeof AuthenticatedAdminAkunIndexRoute
  '/_authenticated/admin/keuangan/': typeof AuthenticatedAdminKeuanganIndexRoute
  '/_authenticated/admin/koppoin/': typeof AuthenticatedAdminKoppoinIndexRoute
  '/_authenticated/admin/profil/': typeof AuthenticatedAdminProfilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/anggota/'
    | '/approval/'
    | '/audit/'
    | '/dokumen/'
    | '/kas-keluar/'
    | '/kas-masuk/'
    | '/konfigurasi-shu/'
    | '/kontrak/'
    | '/laporan/'
    | '/ledger/'
    | '/pengawasan/'
    | '/pengumuman/'
    | '/penukaran-poin/'
    | '/pos/'
    | '/rapat/'
    | '/settings/'
    | '/simpan-pinjam/'
    | '/stok/'
    | '/supplier/'
    | '/tutup-kas/'
    | '/admin/akun/'
    | '/admin/keuangan/'
    | '/admin/koppoin/'
    | '/admin/profil/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/anggota'
    | '/approval'
    | '/audit'
    | '/dokumen'
    | '/kas-keluar'
    | '/kas-masuk'
    | '/konfigurasi-shu'
    | '/kontrak'
    | '/laporan'
    | '/ledger'
    | '/pengawasan'
    | '/pengumuman'
    | '/penukaran-poin'
    | '/pos'
    | '/rapat'
    | '/settings'
    | '/simpan-pinjam'
    | '/stok'
    | '/supplier'
    | '/tutup-kas'
    | '/admin/akun'
    | '/admin/keuangan'
    | '/admin/koppoin'
    | '/admin/profil'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/anggota/'
    | '/_authenticated/approval/'
    | '/_authenticated/audit/'
    | '/_authenticated/dokumen/'
    | '/_authenticated/kas-keluar/'
    | '/_authenticated/kas-masuk/'
    | '/_authenticated/konfigurasi-shu/'
    | '/_authenticated/kontrak/'
    | '/_authenticated/laporan/'
    | '/_authenticated/ledger/'
    | '/_authenticated/pengawasan/'
    | '/_authenticated/pengumuman/'
    | '/_authenticated/penukaran-poin/'
    | '/_authenticated/pos/'
    | '/_authenticated/rapat/'
    | '/_authenticated/settings/'
    | '/_authenticated/simpan-pinjam/'
    | '/_authenticated/stok/'
    | '/_authenticated/supplier/'
    | '/_authenticated/tutup-kas/'
    | '/_authenticated/admin/akun/'
    | '/_authenticated/admin/keuangan/'
    | '/_authenticated/admin/koppoin/'
    | '/_authenticated/admin/profil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tutup-kas/': {
      id: '/_authenticated/tutup-kas/'
      path: '/tutup-kas'
      fullPath: '/tutup-kas/'
      preLoaderRoute: typeof AuthenticatedTutupKasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/': {
      id: '/_authenticated/supplier/'
      path: '/supplier'
      fullPath: '/supplier/'
      preLoaderRoute: typeof AuthenticatedSupplierIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stok/': {
      id: '/_authenticated/stok/'
      path: '/stok'
      fullPath: '/stok/'
      preLoaderRoute: typeof AuthenticatedStokIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simpan-pinjam/': {
      id: '/_authenticated/simpan-pinjam/'
      path: '/simpan-pinjam'
      fullPath: '/simpan-pinjam/'
      preLoaderRoute: typeof AuthenticatedSimpanPinjamIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/rapat/': {
      id: '/_authenticated/rapat/'
      path: '/rapat'
      fullPath: '/rapat/'
      preLoaderRoute: typeof AuthenticatedRapatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos/': {
      id: '/_authenticated/pos/'
      path: '/pos'
      fullPath: '/pos/'
      preLoaderRoute: typeof AuthenticatedPosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/penukaran-poin/': {
      id: '/_authenticated/penukaran-poin/'
      path: '/penukaran-poin'
      fullPath: '/penukaran-poin/'
      preLoaderRoute: typeof AuthenticatedPenukaranPoinIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengumuman/': {
      id: '/_authenticated/pengumuman/'
      path: '/pengumuman'
      fullPath: '/pengumuman/'
      preLoaderRoute: typeof AuthenticatedPengumumanIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengawasan/': {
      id: '/_authenticated/pengawasan/'
      path: '/pengawasan'
      fullPath: '/pengawasan/'
      preLoaderRoute: typeof AuthenticatedPengawasanIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ledger/': {
      id: '/_authenticated/ledger/'
      path: '/ledger'
      fullPath: '/ledger/'
      preLoaderRoute: typeof AuthenticatedLedgerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/laporan/': {
      id: '/_authenticated/laporan/'
      path: '/laporan'
      fullPath: '/laporan/'
      preLoaderRoute: typeof AuthenticatedLaporanIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kontrak/': {
      id: '/_authenticated/kontrak/'
      path: '/kontrak'
      fullPath: '/kontrak/'
      preLoaderRoute: typeof AuthenticatedKontrakIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/konfigurasi-shu/': {
      id: '/_authenticated/konfigurasi-shu/'
      path: '/konfigurasi-shu'
      fullPath: '/konfigurasi-shu/'
      preLoaderRoute: typeof AuthenticatedKonfigurasiShuIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kas-masuk/': {
      id: '/_authenticated/kas-masuk/'
      path: '/kas-masuk'
      fullPath: '/kas-masuk/'
      preLoaderRoute: typeof AuthenticatedKasMasukIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kas-keluar/': {
      id: '/_authenticated/kas-keluar/'
      path: '/kas-keluar'
      fullPath: '/kas-keluar/'
      preLoaderRoute: typeof AuthenticatedKasKeluarIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dokumen/': {
      id: '/_authenticated/dokumen/'
      path: '/dokumen'
      fullPath: '/dokumen/'
      preLoaderRoute: typeof AuthenticatedDokumenIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit/': {
      id: '/_authenticated/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuthenticatedAuditIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approval/': {
      id: '/_authenticated/approval/'
      path: '/approval'
      fullPath: '/approval/'
      preLoaderRoute: typeof AuthenticatedApprovalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anggota/': {
      id: '/_authenticated/anggota/'
      path: '/anggota'
      fullPath: '/anggota/'
      preLoaderRoute: typeof AuthenticatedAnggotaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/profil/': {
      id: '/_authenticated/admin/profil/'
      path: '/admin/profil'
      fullPath: '/admin/profil/'
      preLoaderRoute: typeof AuthenticatedAdminProfilIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/koppoin/': {
      id: '/_authenticated/admin/koppoin/'
      path: '/admin/koppoin'
      fullPath: '/admin/koppoin/'
      preLoaderRoute: typeof AuthenticatedAdminKoppoinIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/keuangan/': {
      id: '/_authenticated/admin/keuangan/'
      path: '/admin/keuangan'
      fullPath: '/admin/keuangan/'
      preLoaderRoute: typeof AuthenticatedAdminKeuanganIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/akun/': {
      id: '/_authenticated/admin/akun/'
      path: '/admin/akun'
      fullPath: '/admin/akun/'
      preLoaderRoute: typeof AuthenticatedAdminAkunIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAnggotaIndexRoute: typeof AuthenticatedAnggotaIndexRoute
  AuthenticatedApprovalIndexRoute: typeof AuthenticatedApprovalIndexRoute
  AuthenticatedAuditIndexRoute: typeof AuthenticatedAuditIndexRoute
  AuthenticatedDokumenIndexRoute: typeof AuthenticatedDokumenIndexRoute
  AuthenticatedKasKeluarIndexRoute: typeof AuthenticatedKasKeluarIndexRoute
  AuthenticatedKasMasukIndexRoute: typeof AuthenticatedKasMasukIndexRoute
  AuthenticatedKonfigurasiShuIndexRoute: typeof AuthenticatedKonfigurasiShuIndexRoute
  AuthenticatedKontrakIndexRoute: typeof AuthenticatedKontrakIndexRoute
  AuthenticatedLaporanIndexRoute: typeof AuthenticatedLaporanIndexRoute
  AuthenticatedLedgerIndexRoute: typeof AuthenticatedLedgerIndexRoute
  AuthenticatedPengawasanIndexRoute: typeof AuthenticatedPengawasanIndexRoute
  AuthenticatedPengumumanIndexRoute: typeof AuthenticatedPengumumanIndexRoute
  AuthenticatedPenukaranPoinIndexRoute: typeof AuthenticatedPenukaranPoinIndexRoute
  AuthenticatedPosIndexRoute: typeof AuthenticatedPosIndexRoute
  AuthenticatedRapatIndexRoute: typeof AuthenticatedRapatIndexRoute
  AuthenticatedSimpanPinjamIndexRoute: typeof AuthenticatedSimpanPinjamIndexRoute
  AuthenticatedStokIndexRoute: typeof AuthenticatedStokIndexRoute
  AuthenticatedSupplierIndexRoute: typeof AuthenticatedSupplierIndexRoute
  AuthenticatedTutupKasIndexRoute: typeof AuthenticatedTutupKasIndexRoute
  AuthenticatedAdminAkunIndexRoute: typeof AuthenticatedAdminAkunIndexRoute
  AuthenticatedAdminKeuanganIndexRoute: typeof AuthenticatedAdminKeuanganIndexRoute
  AuthenticatedAdminKoppoinIndexRoute: typeof AuthenticatedAdminKoppoinIndexRoute
  AuthenticatedAdminProfilIndexRoute: typeof AuthenticatedAdminProfilIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAnggotaIndexRoute: AuthenticatedAnggotaIndexRoute,
  AuthenticatedApprovalIndexRoute: AuthenticatedApprovalIndexRoute,
  AuthenticatedAuditIndexRoute: AuthenticatedAuditIndexRoute,
  AuthenticatedDokumenIndexRoute: AuthenticatedDokumenIndexRoute,
  AuthenticatedKasKeluarIndexRoute: AuthenticatedKasKeluarIndexRoute,
  AuthenticatedKasMasukIndexRoute: AuthenticatedKasMasukIndexRoute,
  AuthenticatedKonfigurasiShuIndexRoute: AuthenticatedKonfigurasiShuIndexRoute,
  AuthenticatedKontrakIndexRoute: AuthenticatedKontrakIndexRoute,
  AuthenticatedLaporanIndexRoute: AuthenticatedLaporanIndexRoute,
  AuthenticatedLedgerIndexRoute: AuthenticatedLedgerIndexRoute,
  AuthenticatedPengawasanIndexRoute: AuthenticatedPengawasanIndexRoute,
  AuthenticatedPengumumanIndexRoute: AuthenticatedPengumumanIndexRoute,
  AuthenticatedPenukaranPoinIndexRoute: AuthenticatedPenukaranPoinIndexRoute,
  AuthenticatedPosIndexRoute: AuthenticatedPosIndexRoute,
  AuthenticatedRapatIndexRoute: AuthenticatedRapatIndexRoute,
  AuthenticatedSimpanPinjamIndexRoute: AuthenticatedSimpanPinjamIndexRoute,
  AuthenticatedStokIndexRoute: AuthenticatedStokIndexRoute,
  AuthenticatedSupplierIndexRoute: AuthenticatedSupplierIndexRoute,
  AuthenticatedTutupKasIndexRoute: AuthenticatedTutupKasIndexRoute,
  AuthenticatedAdminAkunIndexRoute: AuthenticatedAdminAkunIndexRoute,
  AuthenticatedAdminKeuanganIndexRoute: AuthenticatedAdminKeuanganIndexRoute,
  AuthenticatedAdminKoppoinIndexRoute: AuthenticatedAdminKoppoinIndexRoute,
  AuthenticatedAdminProfilIndexRoute: AuthenticatedAdminProfilIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
